//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCCWebsite002
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cadet()
        {
            this.stock_issue = new HashSet<stock_issue>();
        }
    
        public int cadetid { get; set; }
        public string nccregno { get; set; }
        public string cadetname { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string phoneno { get; set; }
        public string course { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_issue> stock_issue { get; set; }
    }
}
