//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCCWebsite002
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrollment
    {
        public int userid { get; set; }
        public string admnno { get; set; }
        public string studentname { get; set; }
        public string dob { get; set; }
        public string gender { get; set; }
        public string phoneno { get; set; }
        public string email { get; set; }
        public string course { get; set; }
        public string year { get; set; }
        public string aboutdesc { get; set; }
        public string reason { get; set; }
    
        public virtual user user { get; set; }
    }
}
