//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCCWebsite002
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_nccEntities : DbContext
    {
        public db_nccEntities()
            : base("name=db_nccEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cadet> cadets { get; set; }
        public virtual DbSet<enrollment> enrollments { get; set; }
        public virtual DbSet<stock_issue> stock_issue { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<tb_event> tb_event { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
