//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCCWebsite002
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int stockid { get; set; }
        public string stockname { get; set; }
        public Nullable<int> stockqty { get; set; }
    
        public virtual stock_issue stock_issue { get; set; }
    }
}
