//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCCWebsite002
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_event
    {
        public int eventid { get; set; }
        public string eventname { get; set; }
        public string eventdate { get; set; }
        public string eventvenue { get; set; }
        public string eventimage { get; set; }
        public string eventdesc { get; set; }
    }
}
